/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rgour;

/**
 *
 * @author gigis
 */
public class agame extends javax.swing.JFrame {

    /**
     * Creates new form agame
     */
    
    public int grabeDice;
    public game controller;
    public agame() {
        initComponents();
    }
    public void setRollDisplay(String rollDisplayStr){
        rollDisplay.setText(rollDisplayStr);
    }
    public void setWhoseTurnDisplay(int x){
        if (x == 1){
            whoseTurnDisplay.setText("Player 1's Turn");
        }else {
            whoseTurnDisplay.setText("Player 2's Turn");
        }
    }
    public String rollDisplayStr;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        fp1 = new javax.swing.JLabel();
        fp2 = new javax.swing.JLabel();
        fp3 = new javax.swing.JLabel();
        fp4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        sp1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        rollButton = new javax.swing.JButton();
        rollDisplay = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        whoversuslabel = new javax.swing.JLabel();
        difficultyLabel = new javax.swing.JLabel();
        whoseTurnDisplay = new javax.swing.JLabel();
        moveButton = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 800));

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setLayout(null);

        fp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/try.png"))); // NOI18N
        jPanel1.add(fp1);
        fp1.setBounds(80, 650, 50, 50);

        fp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/try.png"))); // NOI18N
        jPanel1.add(fp2);
        fp2.setBounds(140, 650, 50, 50);

        fp3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/try.png"))); // NOI18N
        jPanel1.add(fp3);
        fp3.setBounds(200, 650, 50, 50);

        fp4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/try.png"))); // NOI18N
        jPanel1.add(fp4);
        fp4.setBounds(260, 650, 50, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/start.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(330, 420, 100, 100);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tile.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(230, 420, 100, 100);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/whitestar.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 420, 100, 100);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tile.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(130, 320, 100, 100);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/blacktile.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 320, 100, 100);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/blacktile.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(130, 420, 100, 100);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/blacktile.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(230, 320, 100, 100);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/whitestar.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(330, 320, 100, 100);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/blacktile.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(430, 320, 100, 100);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tile.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(530, 320, 100, 100);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/blacktile.png"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(630, 320, 100, 100);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tile.png"))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(730, 320, 100, 100);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/blacktile.png"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(730, 420, 100, 100);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/whitestar.png"))); // NOI18N
        jPanel1.add(jLabel14);
        jLabel14.setBounds(630, 420, 100, 100);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/start.png"))); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(330, 220, 100, 100);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tile.png"))); // NOI18N
        jPanel1.add(jLabel16);
        jLabel16.setBounds(230, 220, 100, 100);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/blacktile.png"))); // NOI18N
        jPanel1.add(jLabel17);
        jLabel17.setBounds(130, 220, 100, 100);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/whitestar.png"))); // NOI18N
        jPanel1.add(jLabel18);
        jLabel18.setBounds(30, 220, 100, 100);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/blacktile.png"))); // NOI18N
        jPanel1.add(jLabel19);
        jLabel19.setBounds(730, 220, 100, 100);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/whitestar.png"))); // NOI18N
        jPanel1.add(jLabel20);
        jLabel20.setBounds(630, 220, 100, 100);

        sp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/try2.png"))); // NOI18N
        jPanel1.add(sp1);
        sp1.setBounds(90, 110, 50, 50);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/try2.png"))); // NOI18N
        jPanel1.add(jLabel21);
        jLabel21.setBounds(150, 110, 50, 50);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/try2.png"))); // NOI18N
        jPanel1.add(jLabel22);
        jLabel22.setBounds(210, 110, 50, 50);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/try2.png"))); // NOI18N
        jPanel1.add(jLabel23);
        jLabel23.setBounds(270, 110, 50, 50);

        rollButton.setText("roll");
        rollButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollButtonActionPerformed(evt);
            }
        });
        jPanel1.add(rollButton);
        rollButton.setBounds(700, 640, 100, 23);

        rollDisplay.setText("Please Roll");
        jPanel1.add(rollDisplay);
        rollDisplay.setBounds(860, 570, 150, 30);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(jLabel25);
        jLabel25.setBounds(920, 550, 60, 70);

        exitButton.setText("exit game");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(exitButton);
        exitButton.setBounds(10, 10, 120, 23);

        whoversuslabel.setText("vs AI");
        jPanel1.add(whoversuslabel);
        whoversuslabel.setBounds(210, 20, 80, 14);
        whoversuslabel.getAccessibleContext().setAccessibleName("whoverseslabel");

        difficultyLabel.setText("difficulty: easy");
        jPanel1.add(difficultyLabel);
        difficultyLabel.setBounds(320, 20, 140, 14);
        difficultyLabel.getAccessibleContext().setAccessibleName("difficultylabel");

        whoseTurnDisplay.setText("Player 1's turn");
        jPanel1.add(whoseTurnDisplay);
        whoseTurnDisplay.setBounds(450, 20, 100, 14);
        whoseTurnDisplay.getAccessibleContext().setAccessibleName("whoseturnlabel");

        moveButton.setText("move");
        moveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveButtonActionPerformed(evt);
            }
        });
        jPanel1.add(moveButton);
        moveButton.setBounds(840, 30, 70, 23);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "move piece 1", "move piece 2", "move picece 3", "move piece 4" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(700, 30, 120, 20);

        jLayeredPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1033, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rollButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollButtonActionPerformed
        // TODO add your handling code here:
        //diceRoll d = new diceRoll();
        //int rollResult = d.getDice();
        //rollDisplayStr = "You Rolled: " + rollResult;
        //rollDisplay.setText(rollDisplayStr);
        controller.roll();
    }//GEN-LAST:event_rollButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
            controller.isdone = true;
    }//GEN-LAST:event_exitButtonActionPerformed

    private void moveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveButtonActionPerformed
        // TODO add your handling code here:
        controller.move();
    }//GEN-LAST:event_moveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agame().setVisible(true);
            }
        });
    }
    public void setDificulty(){
        if(controller.easy == true){
        difficultyLabel.setText("Difficulty: easy");
        }else{
            difficultyLabel.setText("Difficulty: hard");
        }
        EmptyDIfficultyLabel();
    }

    public void vsAi(){
        whoversuslabel.setText("Vs AI");
    }
    public void vsPlayer(){
        whoversuslabel.setText("Vs Player");
    }
    public void EmptyDIfficultyLabel(){
        if(controller.vsAi == false){
            difficultyLabel.setText("");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel difficultyLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel fp1;
    private javax.swing.JLabel fp2;
    private javax.swing.JLabel fp3;
    private javax.swing.JLabel fp4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton moveButton;
    private javax.swing.JButton rollButton;
    private javax.swing.JLabel rollDisplay;
    private javax.swing.JLabel sp1;
    private javax.swing.JLabel whoseTurnDisplay;
    private javax.swing.JLabel whoversuslabel;
    // End of variables declaration//GEN-END:variables
}
